// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulePlanner.Infrastructure;

#nullable disable

namespace SchedulePlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SchedulePlanner.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("SchedulePlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchedulePlanner.Domain.Entities.CalendarEvent", b =>
                {
                    b.OwnsOne("SchedulePlanner.Domain.Entities.AttributeData", "AttributeData", b1 =>
                        {
                            b1.Property<Guid>("CalendarEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Attributes");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("CalendarEvents");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId");
                        });

                    b.Navigation("AttributeData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
